config/routes.rb
Blog::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'  
  root to: 'articles#index'
  resources :static_pages
  resources :users
  resources :sessions
  resources :password_resets
  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author_name, :name, :content, :user, :sticky

  has_many :comments
  
  belongs_to :user
  
  before_save { inject_time(:published_at) }
  
  def inject_time(column)
    begin
      self[column] = Time.zone.now
    end while Article.exists?(column => self[column])
  end
end

app/models/permissions.rb
module Permissions
  def self.permission_for(user)
    if user.nil?
      GuestPermission.new
    elsif user.admin?
      AdminPermission.new(user)
    else
      MemberPermission.new(user)
    end
  end
end

app/models/permissions/admin_permission.rb
module Permissions
  class AdminPermission < BasePermission
    def initialize(user)
      allow_all
    end
  end
end

app/models/permissions/base_permission.rb
module Permissions
  class BasePermission
    def allow?(controller, action, resource = nil)
      allowed = @allow_all || @allowed_actions[[controller.to_s, action.to_s]]
      allowed && (allowed == true || resource && allowed.call(resource))
    end
    
    def allow_all
      @allow_all = true
    end

    def allow(controllers, actions, &block)
      @allowed_actions ||= {}
      Array(controllers).each do |controller|
        Array(actions).each do |action|
          @allowed_actions[[controller.to_s, action.to_s]] = block || true
        end
      end
    end
    
    def allow_param(resources, attributes)
      @allowed_params ||= {}
      Array(resources).each do |resource|
        @allowed_params[resource] ||= []
        @allowed_params[resource] += Array(attributes)
      end
    end

    def allow_param?(resource, attribute)
      if @allow_all
        true
      elsif @allowed_params && @allowed_params[resource]
        @allowed_params[resource].include? attribute
      end
    end

    def permit_params!(params)
      if @allow_all
        params.permit!
      elsif @allowed_params
        @allowed_params.each do |resource, attributes|
          if params[resource].respond_to? :permit
            params[resource] = params[resource].permit(*attributes)
          end
        end
      end
    end
  end
end

app/models/permissions/guest_permission.rb
module Permissions
  class GuestPermission < BasePermission
    def initialize
      allow :password_resets, [:new, :create, :edit, :update, :destroy, :delete]
      allow :static_pages, []
      allow :users, [:new, :create]
      allow :sessions, [:new, :create, :destroy]
      allow :articles, [:index, :show]
    end
  end
end

app/models/permissions/member_permission.rb
module Permissions
  class MemberPermission < BasePermission
    def initialize(user)
      allow :users, [:edit, :update]
      allow :articles, [:new, :create, :index, :show]
      allow :sessions, [:new, :create, :destroy]
      allow :articles, [:edit, :update] do |article|
        article.user_id == user.id
      end
      allow_param :article, [:name]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation, :admin, :password_reset_token, :password_reset_sent_at
  
  has_many :articles
  
  validates_uniqueness_of :email
  validates_presence_of :password, on: :create
  
  before_create { generate_token(:auth_token) }
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authorize
  
  delegate :allow?, to: :current_permission
  helper_method :allow?
  
  delegate :allow_param?, to: :current_permission
  helper_method :allow_param?

private
  
  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def current_permission
    @current_permission ||= Permissions.permission_for(current_user)
  end
  
  def current_resource
    nil
  end

  def authorize
    if current_permission.allow?(params[:controller], params[:action], current_resource)
      current_permission.permit_params! params
    else 
      redirect_to root_path, alert: "Not authorized"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.page(params[:page]).per_page(7).order('sticky DESC').order('created_at DESC')
  end

  def show
    @article = current_resource
  end

  def edit
    @article = current_resource
  end

  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    @article.user = current_user
    if @article.save
      redirect_to @article, notice: "Article has been created."
    else
      render :new
    end
  end
  
  def update
    @article = current_resource
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: "Article has been updated."
    else
      render "edit"
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.delete
    redirect_to root_url, notice: "Article removed!"
  end
  
private
  
  def current_resource
    @current_resource ||= Article.find(params[:id]) if params[:id]
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, notice: "Email sent with password reset instructions."
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, alert: "Password reset has expired"
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, notice: "Password has been reset!"
    else 
      render :edit, alert: "Password confirmation doesn't match Password"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin"
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      cookies.permanent[:auth_token] = user.auth_token
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, notice: "Updated profile."
    else
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article_line.html.erb
<div class="article">
  <h2>
    <%= link_to article.name, article %>
  </h2>
  <div class="info">
    by <%= article.author_name %>
    on <%= article.published_at.strftime('%b %d, %Y') %>
  </div>
  <div class="content">
    <%= "Sticky |" if article.sticky? %>
    <% if allow? 'articles', 'destroy', article %>
     <%= link_to 'Delete |', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% if allow? 'articles', 'edit', article %>
     <%= link_to 'Edit', edit_article_path(article) %>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 12, :cols => 35 %>
  </div>
  <% if allow_param? :article, :sticky %>
    <div class="field">
      <%= f.check_box :sticky %>
      <%= f.label :sticky %>
    </div>
  <% end %>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<div class="content">
  <% if allow? 'articles', 'new' %>
    <%= link_to "Create new article", new_article_path %>
  <% end %>
</div>

<div id="articles">
  <%= will_paginate @products, previous_label: h("<"), next_label: h(">") %>
  <% @articles.each do |article| %>
    <%= render partial: 'article_line', locals: { article: article } %>
  <% end %>
  <%= will_paginate @products, previous_label: h("<"), next_label: h(">") %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.name %></h1>
<%= @article.content %>
<p>
  <% if allow? 'articles', 'edit', @article %>
    <%= link_to "Edit", edit_article_path(@article) %> |
  <% end %>
  <%= link_to "Browse Articles", articles_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="header">
      <%=h link_to "Homepage", root_path %>
    </div>
    <div id="container">
      <div id="user_header">
		  <% if current_user %>
		    Logged in as <%= current_user.email %>.
        <%= link_to "My Profile", edit_user_path(current_user.id) %> | 
		    <%= link_to "Log Out", logout_path %>
		  <% else %>
		    <%= link_to "Sign Up", signup_path %> or
		    <%= link_to "Log In", login_path %>
		  <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
    <div class="footer">
      <ul>
        <li><%= link_to "Static page", static_pages_path %></li>
      </ul>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <% if allow_param? :user, :admin %>
    <div class="field">
      <%= f.check_box :admin %>
      <%= f.label :admin %>
    </div>
  <% end %>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<%= render "form" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>